apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-storage
  name: redis-storage
spec:
  containers:
  - image: redis:alpine
    name: redis-storage
    volumeMounts:
    - mountPath: /data/redis
      name: empty-dir-volume
  volumes:
  - name: empty-dir-volume
    emptyDir:
      sizeLimit: 500Mi
