apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: react-app
  name: react-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: react-app
status:
  loadBalancer: {}
