apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: p-xotam
  name: pod-deploy-full-access
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployments"]
  verbs: ["get", "watch", "list", "create", "delete"]
