apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 10
  nodeName: node02
  dnsPolicy: ClusterFirst
  restartPolicy: Always
